name: 'Setup Cloud Custodian'
description: 'Set up the latest version of cloud custodian and add the
   CLI to the PATH'
branding:
  icon: play-circle
  color: yellow
inputs:
  custodian-version:
    description: "Install a particular version of cloud custodian"
runs:
  using: "composite"
  steps:
  - name: "Install cloud custodian"
    shell: "bash"
    run: |
      python3 -m venv custodian
      source custodian/bin/activate
      VERSION_ARG=""
      if [ "${{ inputs.custodian-version }}" ]; then
        VERSION_ARG="== ${{ inputs.custodian-version }}"
      fi
      pip install --quiet -Iv c7n"${VERSION_ARG}"
      dir=$(pwd)
      echo ${HOME}
      mkdir -p ${HOME}/bin
      cat << EOF > ${HOME}/bin/custodian
      #!/bin/bash
      source ${dir}/custodian/bin/activate
      export PATH=${HOME}/bin/:${PATH}
      custodian "\$@"
      EOF
      chmod +x ${HOME}/bin/custodian   
